queue_rules:
  - name: regular
    queue_conditions:
      - &id001
        and:
          - "#approved-reviews-by>=0"
          - "#review-requested=0"
          - label=merge
    merge_conditions: []
    allow_inplace_checks: false
    checks_timeout: 2h
    disallow_checks_interruption_from_queues:
      - regular
    batch_size: 16
    batch_max_wait_time: 2m
    merge_method: merge

pull_request_rules:
  - name: Regular
    conditions: []
    actions:
      queue:

priority_rules:
  - name: Priority rule `high` from queue `regular`
    conditions:
      - label=priority-merge
      - *id001
    priority: high
    allow_checks_interruption: true

  - name: Priority rule `medium` from queue `regular`
    conditions:
      - label=merge
      - *id001
    priority: medium
    allow_checks_interruption: true

  - name: Priority rule `low` from queue `regular`
    conditions:
      - label=merge
      - *id001
    priority: low
    allow_checks_interruption: true
