name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Run a local action
        uses: actions/setup-node
      - name: just local action
        uses: ./.github/workflows/.reusable-deploy.yaml

# Do not collect this one        
# - name: Run a local action
#        uses: actions/setup-node
