name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v14

      - name: Run a local action
        uses: actions/setup-node

# Do not collect this one        
# - name: Run a local action
#        uses: actions/setup-node
# Do not collect this one        
# - name: Run a local action
#        uses: actions/setup-node
